services:

  traefik:
    restart: always
    image: "traefik:v3.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
      - "./config/traefik/traefik.yml:/traefik.yml:ro"
      - "./config/traefik/dynamic.yml:/dynamic.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.odl.local`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      ol-network:
        ipv4_address: 172.44.0.200
