services:
  keycloak-db:
    image: postgres:16
    ports:
      - 5432
    volumes:
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
      - ../db/:/mnt/db
    environment:
      POSTGRES_PASSWORD: password

  keycloak:
    build:
      context: .
      args:
        KEYCLOAK_THEME_GIT_REF: ${KEYCLOAK_THEME_GIT_REF:-main}
    command:
      - "start-dev"
      - "--hostname=https://keycloak.odl.local"
      - "--http-enabled=true"
      - "--features=preview"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
      - "--spi-login-provider=ol-freemarker"
      - "--proxy-headers=xforwarded"
      # - --log-level=DEBUG,de.captaingoldfish:TRACE
      # - --spi-realm-restapi-extension-scim-repair-database=true
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    env_file:
      - path: ./env/keycloak.local.env
        required: false
    volumes:
      - ../repos/ol-keycloak/ol-keycloak/oltheme/target/keycloak-theme-ol-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-theme-ol-1.0-SNAPSHOT.jar
      - ../repos/ol-keycloak/ol-keycloak/ol-spi/target/ol-spi-1.1-SNAPSHOT.jar:/opt/keycloak/providers/ol-spi-1.1-SNAPSHOT.jar
    ports:
      - "8080"
      - "8443"
    networks:
      ol-network:
        ipv4_address: 172.44.1.10
