apisix:
  enable_admin: false
  enable_dev_mode: false
  node_listen: 80
  ssl:
    enable: true
    listen:
      - port: 443

nginx_config:
  error_log_level: debug
  http_configuration_snippet: |
    large_client_header_buffers 4 8k;

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
#END
