apisix:
  enable_admin: false
  enable_dev_mode: false
  ssl:
    enable: true
    listen:
      - port: ${{APISIX_PORT}}

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
#END
