services:
  cms:
    networks:
      default:
      ol-network:
        aliases:
          - cms.openedx.internal.odl.local
  lms:
    networks:
      default:
      ol-network:
        aliases:
          - lms.openedx.internal.odl.local
  mfe:
    networks:
      default:
      ol-network:
        aliases:
          - mfe.openedx.internal.odl.local

networks:
  default:
  ol-network:
    external: true
