services:

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025
      - 1025
    hostname: mail.odl.local
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  webhook-tester:
    image: tarampampam/webhook-tester
    command: --log-json serve --port 8180 --storage-driver redis --pubsub-driver redis --redis-dsn redis://redis:6379/0
    ports: 
      - '8180/tcp'
    depends_on:
      redis: {condition: service_healthy}

  redis:
    image: redis:7-alpine
    volumes: [redis-data:/data:rw]
    ports: ['6379/tcp']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s

volumes:
  redis-data: {}
